GET http://localhost:4004/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJoZXkgaGV5IiwicGFzc3dvcmQiOiIkMmIkMTAkY2dWSFU0dVVTRHIxa1hiRWpjZEw2dVdRNDlqd0pBWi9Tb212TVAubnpLeUd1SkxsaGouclMiLCJmdWxsX25hbWUiOm51bGwsInRpdGxlIjpudWxsLCJlbWFpbCI6bnVsbCwicGhvbmVfbnVtYmVyIjpudWxsLCJsb2NhdGlvbiI6bnVsbCwic2VydmljZXMiOltdLCJ0ZWNobmlxdWUiOltdLCJub3RlcyI6bnVsbCwiZXhwZXJpZW5jZSI6bnVsbCwiYWdlIjpudWxsLCJiaXJ0aGRheSI6bnVsbCwiY3JlYXRpb25EYXRlIjoiMjAyNS0wNC0xNVQxNjoxMzoxMi45NzhaIiwiaWF0IjoxNzQ0NzUyNjMyfQ.nFa2M0IcT4i1qdsu-xhXdksRxwM_PZGCLF2wr-l4bIE
###

POST http://localhost:4004/authentication/user/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
