GET http://localhost:4004/admin/leads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInJvbGUiOiJzdXBlciIsImlhdCI6MTc0NTk1MDY2NywiZXhwIjoxNzQ1OTU0MjY3fQ.6mFinH_NNi2rFhj6e19uZ3tSZ3SKy0u_BMhDW38lEkI
###

POST http://localhost:4004/admin/user/
Content-Type: application/json

{
    "username": "testing",
    "password": "testing"
}

###
POST http://localhost:4004/auth/admin/login
Content-Type: application/json

{
    "username": "initialadmin",
    "password": "AdminPassword123"
}
